services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=inventory_mgmt'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - tmp_pgdata:/var/lib/postgresql/data
    tmpfs:
        - /var/lib/postgresql/data

volumes:
  tmp_pgdata:
    driver: local