spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_mgmt
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres
